import { useCallback, useEffect, useState } from "react";
import { Alert, Box, Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from "@mui/material";
import { IconEdit, IconPlus } from "@tabler/icons-react";
import PageContainer from "../../components/container/PageContainer";
import { useAppSelector } from "../../store/Hooks";
import { hasPermission } from "../../utils/permissions";

export type Field = { key: string; label: string; type?: "text" | "number" | "date" | "select"; options?: string[]; };
export type RecordValue = { id: string; status: string; name?: string };
interface Props<T extends RecordValue> { title: string; singular: string; description: string; fields: Field[]; list: () => Promise<{ items: T[] }>; create: (input: Omit<T, "id">) => Promise<T>; update: (id: string, input: Omit<T, "id">) => Promise<T>; }
const errorMessage = (error: unknown) => typeof error === "object" && error !== null && "response" in error ? (error as { response?: { data?: { error?: { message?: string }; message?: string } } }).response?.data?.error?.message ?? (error as { response?: { data?: { message?: string } } }).response?.data?.message ?? "Unable to save changes." : "Unable to save changes.";

export default function SimpleAcademicResourcePage<T extends RecordValue>({ title, singular, description, fields, list, create, update }: Props<T>) {
    const canManage = hasPermission(useAppSelector((state) => state.permissions.permissions), "academic.manage");
    const [items, setItems] = useState<T[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [selected, setSelected] = useState<T | null>(null); const [open, setOpen] = useState(false); const [form, setForm] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
    const load = useCallback(async () => { setLoading(true); setError(null); try { setItems((await list()).items); } catch { setError(`Unable to load ${title.toLowerCase()}.`); } finally { setLoading(false); } }, [list, title]);
    useEffect(() => { void load(); }, [load]);
    const openForm = (item: T | null) => { const values = item as Record<string, string | number> | null; setSelected(item); setForm(Object.fromEntries(fields.map((field) => [field.key, String(values?.[field.key] ?? (field.key === "status" ? field.options?.[0] ?? "" : ""))]))); setFormError(null); setOpen(true); };
    const submit = async () => { if (fields.some((field) => !form[field.key]?.trim())) { setFormError("Please complete all required fields."); return; } const payload = Object.fromEntries(fields.map((field) => [field.key, field.type === "number" ? Number(form[field.key]) : form[field.key]])) as Omit<T, "id">; if (fields.some((field) => field.type === "number" && !Number.isInteger(payload[field.key] as number))) { setFormError("Number fields must contain whole numbers."); return; } setSaving(true); setFormError(null); try { if (selected) await update(selected.id, payload); else await create(payload); setOpen(false); setSuccess(`${singular} ${selected ? "updated" : "created"} successfully.`); await load(); } catch (err) { setFormError(errorMessage(err)); } finally { setSaving(false); } };
    return <PageContainer title={title} description={description}><Box sx={{ p: { xs: 2, sm: 3 } }}><Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 2, mb: 3 }}><Box><Typography variant="h4">{title}</Typography><Typography color="text.secondary">{description}</Typography></Box>{canManage && <Button variant="contained" startIcon={<IconPlus size={18} />} onClick={() => openForm(null)}>Add {singular}</Button>}</Box>{success && <Alert severity="success" onClose={() => setSuccess(null)} sx={{ mb: 2 }}>{success}</Alert>}{loading ? <Box sx={{ display: "flex", justifyContent: "center", py: 8 }}><CircularProgress /></Box> : error ? <Alert severity="error" action={<Button color="inherit" onClick={() => void load()}>Retry</Button>}>{error}</Alert> : <Paper><TableContainer><Table><TableHead><TableRow>{fields.map((field) => <TableCell key={field.key}>{field.label}</TableCell>)}{canManage && <TableCell align="right">Actions</TableCell>}</TableRow></TableHead><TableBody>{items.length === 0 ? <TableRow><TableCell colSpan={fields.length + (canManage ? 1 : 0)} align="center" sx={{ py: 5 }}>No {title.toLowerCase()} found</TableCell></TableRow> : items.map((item) => { const values = item as Record<string, string | number>; return <TableRow key={item.id} hover>{fields.map((field) => <TableCell key={field.key}>{field.key === "status" ? <Chip label={String(values[field.key])} size="small" color={values[field.key] === "ACTIVE" ? "success" : "default"} /> : String(values[field.key])}</TableCell>)}{canManage && <TableCell align="right"><IconButton aria-label={`Edit ${item.name}`} onClick={() => openForm(item)}><IconEdit size={18} /></IconButton></TableCell>}</TableRow>; })}</TableBody></Table></TableContainer></Paper>}</Box><Dialog open={open} onClose={() => !saving && setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{selected ? "Edit" : "Add"} {singular}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{formError && <Alert severity="error">{formError}</Alert>}{fields.map((field) => field.type === "select" ? <TextField key={field.key} select label={field.label} value={form[field.key] ?? ""} onChange={(e) => setForm({ ...form, [field.key]: e.target.value })}>{field.options?.map((option) => <MenuItem key={option} value={option}>{option}</MenuItem>)}</TextField> : <TextField key={field.key} required label={field.label} type={field.type ?? "text"} value={form[field.key] ?? ""} onChange={(e) => setForm({ ...form, [field.key]: e.target.value })} />)}</Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)} disabled={saving}>Cancel</Button><Button variant="contained" onClick={() => void submit()} disabled={saving}>{saving ? "Saving…" : "Save"}</Button></DialogActions></Dialog></PageContainer>;
}
